### ISSUE TITLE
ViewModel不用了么？

### ISSUE THREAD

**Issue by mxdlsm** [SaltedFish-Extreme/WanAndroid#2]
大佬如果不是列表数据，像详情或者头部这种信息的请求也写在activity/fragment中么？

**Comment by SaltedFish-Extreme** [comment]
> 大佬如果不是列表数据，像详情或者头部这种信息的请求也写在activity/fragment中么？

嗯，我没用mvvm，太麻烦了，直接全写在activity和fragment里的，详情也不过就是个页面，获取数据写在对应的位置就行了，头部比如banner的话我也是写在页面请求里的，详见mainFragment

**Comment by mxdlsm** [comment]
好的谢谢您

**Comment by SaltedFish-Extreme** [comment]
> 好的谢谢您

嗯，有不懂的可以再问我，虽然我也不一定能解答上来😂

**Comment by mxdlsm** [comment]
好的，谢谢
